<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.mixpanel</groupId>
    <artifactId>mixpanel-java-openfeature-provider</artifactId>
    <version>1.7.0</version>
    <packaging>jar</packaging>
    <name>Mixpanel Java SDK - OpenFeature Provider</name>
    <description>
        <![CDATA[OpenFeature provider for the Mixpanel Java SDK. Integrates Mixpanel feature flags with the OpenFeature standard.]]>
    </description>

    <url>https://github.com/mixpanel/mixpanel-java</url>

    <licenses>
        <license>
            <name>The Apache Software License, Version 2.0</name>
            <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
            <distribution>repo</distribution>
            <comments>A business-friendly OSS license</comments>
        </license>
    </licenses>

    <scm>
        <connection>scm:git:https://github.com/mixpanel/mixpanel-java.git</connection>
        <developerConnection>scm:git:git@github.com:mixpanel/mixpanel-java.git</developerConnection>
        <url>https://github.com/mixpanel/mixpanel-java</url>
    </scm>

    <developers>
        <developer>
            <id>mixpanel</id>
            <name>Mixpanel, Inc</name>
            <email>dev@mixpanel.com</email>
            <url>http://www.mixpanel.com</url>
        </developer>
    </developers>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.2.5</version>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>com.mixpanel</groupId>
            <artifactId>mixpanel-java</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>dev.openfeature</groupId>
            <artifactId>sdk</artifactId>
            <version>1.20.1</version>
        </dependency>

        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.13.2</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <version>4.11.0</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
